// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tldgelirindfmtjnbemw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsZGdlbGlyaW5kZm10am5iZW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzMwOTYsImV4cCI6MjA2OTQ0OTA5Nn0.1QR9fUhDniUUEoQyAEfVE5Vms6jlErduKV-QAC7UyOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});